// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class UntitledTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        //driver = new ChromeDriver();
        //js = (IJavaScriptExecutor)driver;
        //vars = new Dictionary<string, object>();
        ChromeOptions options = new ChromeOptions();
        options.AddArgument("--start-maximized");
        ChromeDriverService service = ChromeDriverService.CreateDefaultService("D:\\chromedriver-win64");
        driver = new ChromeDriver(service, options);
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void dangNhapAdmin()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector("a:nth-child(4) > .MuiButtonBase-root")).Click();
        driver.FindElement(By.Id("username")).Click();
        driver.FindElement(By.Id("username")).SendKeys("gv001");
        driver.FindElement(By.Id("password")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".MuiButtonBase-root"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        Thread.Sleep(3000);
        driver.FindElement(By.Id("password")).SendKeys("Gv001");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".MuiButtonBase-root")).Click();
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Thread.Sleep(3000);
        TearDown();
    }
    [Test]
    public void dangNhapGV()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector("a:nth-child(4) > .MuiButtonBase-root")).Click();
        driver.FindElement(By.Id("username")).Click();
        driver.FindElement(By.Id("username")).SendKeys("gv0002");
        driver.FindElement(By.Id("password")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".MuiButtonBase-root"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        Thread.Sleep(3000);
        driver.FindElement(By.Id("password")).SendKeys("Gv0002");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".MuiButtonBase-root")).Click();
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Thread.Sleep(3000);
        TearDown();
    }
    [Test]
    public void dangNhapHS()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector("a:nth-child(4) > .MuiButtonBase-root")).Click();
        driver.FindElement(By.Id("username")).Click();
        driver.FindElement(By.Id("username")).SendKeys("HS01");
        driver.FindElement(By.Id("password")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".MuiButtonBase-root"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        Thread.Sleep(3000);
        driver.FindElement(By.Id("password")).SendKeys("Hs01");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".MuiButtonBase-root")).Click();
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Thread.Sleep(3000);
        TearDown();
    }
    [Test]
    public void chiNhapMatKhau()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector("a:nth-child(4) > .MuiButtonBase-root")).Click();
        Thread.Sleep(3000);
        driver.FindElement(By.Id("password")).Click();
        driver.FindElement(By.Id("password")).SendKeys("123");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".MuiButtonBase-root")).Click();
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Thread.Sleep(3000);
        TearDown();
    }
    [Test]
    public void chiNhapUserName()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector("a:nth-child(4) > .MuiButtonBase-root")).Click();
        driver.FindElement(By.Id("username")).Click();
        driver.FindElement(By.Id("username")).SendKeys("HS01");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".MuiButtonBase-root")).Click();
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Thread.Sleep(3000);
        TearDown();
    }
    [Test]
    public void dangNhapSaiUserName()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector("a:nth-child(4) > .MuiButtonBase-root")).Click();
        driver.FindElement(By.Id("username")).Click();
        driver.FindElement(By.Id("username")).SendKeys("gv0002");
        driver.FindElement(By.Id("password")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".MuiButtonBase-root"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        Thread.Sleep(3000);
        driver.FindElement(By.Id("password")).SendKeys("Gv0001");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".MuiButtonBase-root")).Click();
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Thread.Sleep(3000);
        TearDown();
    }
    [Test]
    public void dangNhapSaiPassword()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector("a:nth-child(4) > .MuiButtonBase-root")).Click();
        driver.FindElement(By.Id("username")).Click();
        driver.FindElement(By.Id("username")).SendKeys("gv0001");
        driver.FindElement(By.Id("password")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".MuiButtonBase-root"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        Thread.Sleep(3000);
        driver.FindElement(By.Id("password")).SendKeys("Gv0002");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".MuiButtonBase-root")).Click();
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Thread.Sleep(3000);
        TearDown();
    }
}
